### ISSUE TITLE
Input et contrôle de saisie

### ISSUE THREAD

**Issue by ljoboy** [CHRINOVIC-MM/Gestion_Hopital#3]
Normalement les fonctions dans docteur et patient ne devraient pas contenir des inputs mais plutot des paramètres et les inputs seraient dans les différents choix de menus, ceci facilite la migration des UI par conséquent les contrôles de saisie ne peuvent pas être dans ces fonctions là

**Comment by geekPastor** [comment]
Pouvez-vous être un peu clair sur cette remarque car je ne l'ai pas bien comprise svp

**Comment by ljoboy** [comment]
Je t'envoie un exemple dans quelque instant

**Comment by ljoboy** [comment]
Ex: `def creer_docteur(nom, prenom, postnom):
          # ton code ici

     # Dans la fonction principale
      nom = input("nom")     
      prenom = input("prenom")     
      postnom = input("postnom")
      creer_docteur(nom, prenom, postnom)`
