### ISSUE TITLE
Docteur a un problème 

### ISSUE THREAD

**Issue by ljoboy** [CHRINOVIC-MM/Gestion_Hopital#4]
La création d'un docteur et l'affectation des horaires ne sont pas des actions simultanées. Un docteur peut ne pas avoir d'horaire

**Comment by geekPastor** [comment]
Oui oui !
Voilà pourquoi je commence par demander si on veut ou pas enregistrer directement l'horaire d'un docteur au moment où on l'enregistre

J'ai mis une structure conditionnelle pour vérifier ça

**Comment by ljoboy** [comment]
Tu ne le fais pas au bon endroit

Le jeu. 19 mai 2022 à 20:47, Chrinovic MUKEBA ***@***.***> a
écrit :
